version: '3'

services:
  garbanzo:
    build: .
    container_name: garbanzo
    command: >
      sh -c "flask db migrate && flask db upgrade && flask run -h 0.0.0.0 -p 5000"
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./src:/garbanzo:cached
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POSTGRES_USERNAME=garbanzo
      - POSTGRES_PASSWORD=WowSuchSecure123
    networks:
      - app-tier
    depends_on:
      - postgresql

  postgresql:
    image: docker.io/bitnami/postgresql:11.11.0-debian-10-r16 
    container_name: postgresql
    volumes:
      - postgresql_data:/bitnami/postgresql:rw # this mounts the docker-managed elasticsearch_data volume into the container and makes it writable
    environment:
      - POSTGRESQL_USERNAME=garbanzo
      - POSTGRESQL_PASSWORD=WowSuchSecure123
      - POSTGRESQL_DATABASE=garbanzo
      - POSTGRESQL_POSTGRES_PASSWORD=IamTheCaptainNow
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  postgresql_data:
