apiVersion: v1
kind: Service
metadata:
  name: {{ include "garbanzo.fullname" . }}
  labels:
    {{- include "garbanzo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "garbanzo.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
